[package]
name = "strip-json-comments-native"
version = "1.0.0"
edition = "2021"
authors = ["sogoiii"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi.workspace = true
napi-derive.workspace = true

[build-dependencies]
napi-build = "2"
